name: Install Django and Run Tests

on:
  push:
    branches: [ "main" ]

jobs:
  test-django:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]
        django-version: [3.2]  # Replace this with your desired Django version

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Django
      run: |
        python3 -m venv env
        source env/bin/activate
        python3 -m pip install --upgrade pip
        pip install Django==${{ matrix.django-version }}
    - name: Run Django Tests
      run: |
        source env/bin/activate
        python manage.py test
