name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login in to Docker Hub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      run: docker login -u $DOCKER_NAME -p $DOCKER_PASSWORD

    - name: Push Image
      env:
        APP_NAME: "imagee"
      run: |
        docker tag $APP_NAME $DOCKER_NAME/wec
        docker push $DOCKER_NAME/wec
