name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: "jokesta"
        password: "rR1630rR@123"

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag imagee

    - name: Push to Docker Hub
      env:
        DOCKER_USERNAME: "jokesta"
        DOCKER_PASSWORD: "rR1630rR@123"
        IMAGE_NAME: "imagee"
      run: |
